name: Update this repo's README with RSS feed

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://www.vitim.us/feed.json
          readme-section: feed
          empty-commits: false
          max: 7
          template: "- [{{ title }}]({{ url }})  \n  {{ summary }}"
          path: README.md
          
