# https://github.com/gautamkrishnar/blog-post-workflow
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: "0 18 * * Sun"
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in Hashnode posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: https://www.vitim.us/feed.xml
          max_post_count: 3
          commit_message: "Updated README with the latest blog posts"
          date_format: "mmm d, yyyy"
#           custom_tags: "postImage/image/"
          disable_html_encoding: true
#           item_exec: |
#             post.description = post.description.replace(/<\/?[^>]+(>|$)/g, "").slice(0,100)
          template: '<table><tr><td>-</td><td><a href="$url">$title</a> | $date <br> $description... </td></tr></table>$newline'
